# key datastructure in pandas
* series
* dataframe

In [2]:
import pandas as pd
from sklearn.datasets import load_iris

In [3]:
s=pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [4]:
df= pd.DataFrame({"Name": ["Deep", "Alice", "Bob"], "Age": [25, 30, 22], "City": ["Kolkata", "New York", "Los Angeles"]})
df

    Name  Age         City
0   Deep   25      Kolkata
1  Alice   30     New York
2    Bob   22  Los Angeles

In [5]:
dataset=load_iris()

In [6]:
df = pd.DataFrame(data=dataset.data, columns=dataset.feature_names)
df.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [7]:
df["petal length (cm)"]

0      1.4
1      1.4
2      1.3
3      1.5
4      1.4
      ...
145    5.2
146    5.0
147    5.2
148    5.4
149    5.1
Name: petal length (cm), Length: 150, dtype: float64

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB

In [9]:
df2 = pd.DataFrame({"Name": ["Deep","Alice",None, "KK"], "Age": [25,None,30,22]})
df2

    Name   Age
0   Deep  25.0
1  Alice   NaN
2    NaN  30.0
3     KK  22.0

In [10]:
df2.dropna()

   Name   Age
0  Deep  25.0
3    KK  22.0

In [11]:
df2.fillna(0)

    Name   Age
0   Deep  25.0
1  Alice   0.0
2      0  30.0
3     KK  22.0

In [12]:
df.rename(columns={"sepal length (cm)": "SL"}, inplace=True)
df.head()

    SL  sepal width (cm)  petal length (cm)  petal width (cm)
0  5.1               3.5                1.4               0.2
1  4.9               3.0                1.4               0.2
2  4.7               3.2                1.3               0.2
3  4.6               3.1                1.5               0.2
4  5.0               3.6                1.4               0.2

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   SL                 150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB

In [14]:
df["SL"]=df["SL"].astype(int)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   SL                 150 non-null    int64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(3), int64(1)
memory usage: 4.8 KB

In [15]:
len(df)

150

In [17]:
df["zeroes"]= [0 for i in range(len(df))]
df.head()

   SL  sepal width (cm)  petal length (cm)  petal width (cm)  zeroes
0   5               3.5                1.4               0.2       0
1   4               3.0                1.4               0.2       0
2   4               3.2                1.3               0.2       0
3   4               3.1                1.5               0.2       0
4   5               3.6                1.4               0.2       0

In [19]:
def fx(a):
    return a*2
df["PL"]= df["petal length (cm)"].apply(fx)
df.head()

   SL  sepal width (cm)  petal length (cm)  petal width (cm)  zeroes   PL
0   5               3.5                1.4               0.2       0  2.8
1   4               3.0                1.4               0.2       0  2.8
2   4               3.2                1.3               0.2       0  2.6
3   4               3.1                1.5               0.2       0  3.0
4   5               3.6                1.4               0.2       0  2.8

In [20]:
df3 =pd.DataFrame({"Name": ["x", "y", "z"], "Age": [10, 20, 30]})
df3

  Name  Age
0    x   10
1    y   20
2    z   30

In [21]:
df4 =pd.DataFrame({"Name": ["a", "b", "c"], "Age": [40, 50, 60]})
df4

  Name  Age
0    a   40
1    b   50
2    c   60

In [24]:
pd.concat([df3, df4], ignore_index=True)

  Name  Age
0    x   10
1    y   20
2    z   30
3    a   40
4    b   50
5    c   60

In [25]:
df5 =pd.DataFrame({"Name": ["x", "y", "z"], "Salary": [1000, 2000, 3000]})
df5

  Name  Salary
0    x    1000
1    y    2000
2    z    3000

In [ ]:
pd.merge(df3, df5, on="Name")